gantt
	title 결혼 준비
	dateFormat  YYYY-MM-DD

	section 외부요인
    우한폐렴1번확인: done, crit, 2020-01-20, 1d
    3번환자등장: done, crit, 2020-01-26, 1d
    31번환자등장: done, crit, 2020-02-18, 1d
    국내사망발생: done, crit, 2020-02-20, 1d
    이탈리아쇼크: done, crit, 2020-02-23, 1d
    위기경보단계'심각': done, crit, 2020-02-24, 1d
    그리스1번등장: done, crit, 2020-02-27, 1d


  section 예식장준비+본식(50M~)
    그린웨딩신청: done, 2020-01-09, 2d
    그린웨딩당첨&가계약(50M): done, 2020-01-28, 2d
    꽃장식 부케등등 문의: done, 2020-02-03, 1d
    결혼식당일: dday, 2020-07-18  , 1d
  section 스드메(50M~)
    스드메업체컨택: done, 2020-02-04, 2d
    스드메업체1(샐리브라이드)상담: done, 2020-02-09, 1d
    스드메업체2(브라이덜휘)상담&가계약(30M): done, 2020-02-16, 1d
    두 업체 비교를 위한 정리 및 TASK 등록: done, 2020-02-18, 2020-02-21
    스드메업체1(샐리브라이드) 드레스 시착: done, 2020-02-22, 1d
    스드메업체1(샐리브라이드) 계약(50M): done, 2020-02-22, 1d
    스드메업체2(브라이덜휘)가계약환불(-30M): done, 2020-02-22, 2020-02-26
    테일러샵방문: 2020-03-29, 1d
    가봉스냅촬영: 2020-04-29, 1d
    한복시착?(아마도): 2020-05-02, 1d

  section 상견례+예물(0M~)
    제휴예물업체에서상담받아보자: 2020-03-07, 2d
    결혼반지알아보기: 1d

  section 섭외+하객(1M~)
    각자 청첩장 샘플 신청후 검토 (1M): done, 2020-02-10, 2020-02-13
    사회자섭외(김혜준): done, 2020-02-23, 1d
    청첩장의뢰                :1d
    another task             :1d

  section 신혼집(0M~)
    5월 전세집 알아보기 시작: 2020-05-01, 7d

  section 신혼여행(440M~)
    여행사 & 여행지선정(산토리니-아테네&블루여행사): done, 2020-02-03, 2020-02-13
    블루여행사에게서 취소 당함: done, crit, 2020-02-13, 1d
    여행박사에 견적문의 & 예약(120M): done, 2020-02-16, 2020-02-17
    항공권 발권 확인(320M): done, 2020-02-18, 2020-02-20
    잔금결제: 1d

    세부 계획             :1d
    신혼여행: 2020-07-19, 2020-07-26


