gantt
	title 결혼 준비
	dateFormat  YYYY-MM-DD

	section 예식장준비+스드메+본식
    그린웨딩신청: done, 2020-01-09, 2d
    그린웨딩당첨&가계약: done, 2020-01-28, 2d
    꽃장식 부케등등: active, 2020-02-03, 7d
    스드메업체컨택: active, 2020-02-04, 7d
    결혼식당일: dday, 2020-07-18  , 1d

  section 상견례+예물
    another task             :1d

  section 섭외+하객
    청첩장의뢰                :1d
    another task             :1d

  section 신혼집+신혼여행
    여행사 & 여행지선정: 2020-02-03, 7d
    another task             :1d

