graph TB
  subgraph 결혼식 전
    체크리스크작성 & 하객리스트작성 & 순서진행도작성 & 상견례진행 --> 준비끝((끝))
    subgraph 섭외
      주례섭외>주례] --> 섭외완료
      축가섭외>축가] --> 섭외완료
      접수섭외[접수2명섭외] --> 섭외완료
      사회자섭외[사회자] --> 섭외완료
      본식스냅섭외[본식스냅] --> 섭외완료
      스튜디오스냅섭외[스튜디오스냅] --> 섭외완료
    end
    subgraph 하객
      하객리스트작성 --> 하객완료
      청첩장 --> 직장동료 --> 하객완료
      청첩장 --> 대학동기 --> 하객완료
      청첩장 --> 학생회 --> 하객완료
      청첩장 --> 제로페이지 --> 하객완료
    end
    subgraph 예물
      반지(예물:랑) --> 예물완료
      목걸이(예물:랑) --> 예물완료
      시계(예물:랑) --> 예물완료
      양복2벌(예물:랑) --> 예물완료
      한복(예물:랑) --> 예물완료
    end
    subgraph 예식장
      청첩장제출[동양케터링에 청첩장 전달] --> 예식장완료
      피로연시식 --> 예식장완료
    end

    스튜디오스냅섭외 --> 스튜디오촬영 --> 청첩장[청첩장의뢰후수령] --> 청첩장제출

    예식장완료 & 섭외완료 & 예물완료 & 하객완료 --> 준비끝((끝))
  end
  subgraph 결혼식 후
    신혼여행[신혼여행]
  end
  준비끝 --> 결혼식시작
  subgraph 결혼식 당일
    결혼식시작((시작)) --> 드레스_착용
    메이크업
    그린팩토리도착
    예식리허설
    결혼식_메인[결혼식]
    피로연_인사 --> 결혼식끝((끝))

    subgraph 인원도착확인
      본식스냅섭외 --> 본식스냅_도착확인 --> 인원도착확인완료
      주례섭외 -.-> 주례_도착확인 --> 인원도착확인완료
      축가섭외 -.-> 축가_도착확인 --> 인원도착확인완료
      접수섭외 --> 접수_도착확인 --> 인원도착확인완료
    end

    드레스_착용 --> 메이크업 --> 그린팩토리도착

    그린팩토리도착 --> 인원도착확인완료 --> 예식리허설

    예식리허설 --> 결혼식_메인 --> 피로연_인사

  end
