gantt
  title 결혼 준비
  dateFormat  YYYY-MM-DD

  section 외부요인
    우한폐렴1번확인: done, crit, 2020-01-20, 1d
    3번환자등장: done, crit, 2020-01-26, 1d
    31번환자등장: done, crit, 2020-02-18, 1d
    국내사망발생: done, crit, 2020-02-20, 1d
    이탈리아쇼크: done, crit, 2020-02-23, 1d
    위기경보단계'심각': done, crit, 2020-02-24, 1d
    그리스1번등장: done, crit, 2020-02-27, 1d
    문서 공개: done, 2020-03-07, 1d
    구로 콜센터 감염: done, crit, 2020-03-10, 1d
    한국 환자수 변곡점: done, 2020-03-12, 1d
    제주도 모녀 사건: done, crit, 2020-03-26, 1d
    신랑 당직: done, 2020-04-13, 2020-04-20
    21대 총선: done, 2020-04-15, 1d
    신랑 당직: 2020-05-08, 2020-05-15

  section 예식장준비(50M~)
    그린웨딩신청: done, 2020-01-09, 2d
    그린웨딩당첨&가계약(50M): done, 2020-01-28, 2d
    꽃장식 부케등등 문의: done, 2020-02-03, 1d

  section 스드메(130M~)
    스드메업체컨택: done, 2020-02-04, 2d
    스드메업체1(샐****) 상담: done, 2020-02-09, 1d
    스드메업체2(브****) 상담&가계약(30M): done, 2020-02-16, 1d
    두 업체 비교 정리: done, 2020-02-18, 2020-02-21
    스드메업체3(라****) 상담: done, 2020-02-22, 1d
    스드메업체1(샐****) 드레스 시착: done, 2020-02-22, 1d
    스드메업체1(샐****) 계약(50M): done, 2020-02-22, 1d
    스드메업체2(브****) 가계약환불(-30M): done, 2020-02-22, 2020-02-26
    테일러샵 방문(70M): done, 2020-03-29, 1d
    테일러샵 재방문(10M): done, 2020-04-04, 1d
    스냅용 턱시도 픽업: 2020-04-28, 1d
    가봉 스냅 촬영: 2020-04-29, 1d
    어머님 한복 대여: 2020-05-02, 1d

  section 예물(80M~)
    스드메(샐****)제휴 예물 업체(백****) 상담: done, 2020-03-15, 1d
    결혼반지 계약 (백****)(80M): done, 2020-03-15, 1d
    반지 출고 예정일: 2020-04-24, 1d
    촬영 예물 대여 반납: 2020-04-27, 2020-04-30

  section 상견례
    상견례: done, 2020-04-11, 1d

  section 섭외
    사회자섭외(신랑친구): done, 2020-02-23, 1d
    축가섭외(신부친구): done, 2020-02-26, 1d
    주례섭외(신랑교수님): done, 2020-04-17, 1d

  section 하객(1M~)
    각자 청첩장 샘플 신청후 검토 (1M): done, 2020-02-10, 2020-02-13
    청첩장의뢰                : ,

  section 신혼집(0M~)
    성남 구미 무지개마을 구경: done, 2020-04-12, 1d
    용인 상갈 금화마을 구경: done, 2020-04-15, 1d
    5월 전세집 알아보기 시작: 2020-05-01, 7d

  section 본식
    본식용 턱시도 픽업: 2020-07-17, 1d
    결혼식 당일: dday, 2020-07-18, 1d

  section 신혼여행(440M~)
    여행사 & 여행지선정(산토리니-아테네&블****여행사): done, 2020-02-03, 2020-02-13
    블****여행사에게서 취소 당함: done, crit, 2020-02-13, 1d
    여****여행사에 견적문의 & 예약(120M): done, 2020-02-16, 2020-02-17
    항공권 발권 확인(320M): done, 2020-02-18, 2020-02-20
    여행 가능 여부 재고: 2020-05-30, 1d
    잔금결제: 1d
    세부 계획: 1d
    신혼여행: 2020-07-19, 2020-07-26
